package CoryLangWasm.Helpers;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.Deque;
import jetbrains.mps.internal.collections.runtime.LinkedListSequence;
import java.util.LinkedList;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public class InstrHelper {
  public static Iterable<SNode> nodeToInstr(SNode input) {
    final Deque<SNode> outputs = LinkedListSequence.fromLinkedList(new LinkedList<SNode>());

    SAbstractConcept cncpt = SNodeOperations.getConcept(input);
    boolean noneMatched = true;
    if (noneMatched && SConceptOperations.isSubConceptOf(cncpt, CONCEPTS.Const$Wh)) {
      noneMatched = false;
      Sequence.fromIterable(instrForConst(SNodeOperations.as(input, CONCEPTS.Const$Wh))).visitAll((instr) -> LinkedListSequence.fromLinkedListNew(outputs).pushElement(instr));

    }

    return ListSequence.fromList(LinkedListSequence.fromLinkedListNew(outputs).toList()).reversedList();
  }

  public static Iterable<SNode> instrForConst(SNode val) {
    Deque<SNode> outputs = LinkedListSequence.fromLinkedList(new LinkedList<SNode>());

    if (SPropertyOperations.getEnum(val, PROPS.valType$kiC8) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL, "CoryLang.structure.ValueType"), 0x7c255ef74f4f054dL, "i32")) {
      SNode newNode = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x39e7fc40f506bb60L, "WebAssembly.structure.I32Const"));
      SPropertyOperations.assign(newNode, PROPS.value$l9MY, Integer.parseInt(SPropertyOperations.getString(val, PROPS.content$As7s)));
      LinkedListSequence.fromLinkedListNew(outputs).pushElement(newNode);
    } else if (SPropertyOperations.getEnum(val, PROPS.valType$kiC8) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL, "CoryLang.structure.ValueType"), 0x7c255ef74f4f0580L, "i64")) {
      SNode newNode = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x39e7fc40f524766fL, "WebAssembly.structure.I64Const"));
      SPropertyOperations.assign(newNode, PROPS.value$eedi, SPropertyOperations.getString(val, PROPS.content$As7s));
      LinkedListSequence.fromLinkedListNew(outputs).pushElement(newNode);
    } else if (SPropertyOperations.getEnum(val, PROPS.valType$kiC8) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL, "CoryLang.structure.ValueType"), 0x7c255ef74f4f058dL, "f32")) {
      SNode newNode = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x39e7fc40f50cd7bcL, "WebAssembly.structure.F32Const"));
      SPropertyOperations.assign(newNode, PROPS.value$FF8t, SPropertyOperations.getString(val, PROPS.content$As7s));
      LinkedListSequence.fromLinkedListNew(outputs).pushElement(newNode);
    } else if (SPropertyOperations.getEnum(val, PROPS.valType$kiC8) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL, "CoryLang.structure.ValueType"), 0x7c255ef74f4f05a5L, "f64")) {
      SNode newNode = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x39e7fc40f514690eL, "WebAssembly.structure.F64Const"));
      SPropertyOperations.assign(newNode, PROPS.value$xr4t, SPropertyOperations.getString(val, PROPS.content$As7s));
      LinkedListSequence.fromLinkedListNew(outputs).pushElement(newNode);
    }

    return ListSequence.fromList(LinkedListSequence.fromLinkedListNew(outputs).toList()).reversedList();
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Const$Wh = MetaAdapterFactory.getConcept(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e373L, "CoryLang.structure.Const");
  }

  private static final class PROPS {
    /*package*/ static final SProperty value$l9MY = MetaAdapterFactory.getProperty(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x39e7fc40f506bb60L, 0x39e7fc40f506bb83L, "value");
    /*package*/ static final SProperty content$As7s = MetaAdapterFactory.getProperty(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e373L, 0x39e7fc40f9b5e376L, "content");
    /*package*/ static final SProperty valType$kiC8 = MetaAdapterFactory.getProperty(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e373L, 0x7c255ef750435947L, "valType");
    /*package*/ static final SProperty value$eedi = MetaAdapterFactory.getProperty(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x39e7fc40f524766fL, 0x39e7fc40f5247670L, "value");
    /*package*/ static final SProperty value$FF8t = MetaAdapterFactory.getProperty(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x39e7fc40f50cd7bcL, 0x39e7fc40f50cd7bdL, "value");
    /*package*/ static final SProperty value$xr4t = MetaAdapterFactory.getProperty(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x39e7fc40f514690eL, 0x39e7fc40f514690fL, "value");
  }
}
