package CoryLangWasm.Helpers;

/*Generated by MPS */

import java.util.Deque;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.LinkedListSequence;
import java.util.LinkedList;
import CoryLang.behavior.LocalIndexed__BehaviorDescriptor;

public class TransformState {
  private Deque<SNode> funcs;
  private Deque<SNode> locals;



  public TransformState() {
    this.funcs = LinkedListSequence.fromLinkedList(new LinkedList<SNode>());
    this.locals = LinkedListSequence.fromLinkedList(new LinkedList<SNode>());
  }

  public static TransformState empty() {
    return new TransformState();
  }

  public TransformState clone() {
    final TransformState newState = TransformState.empty();
    LinkedListSequence.fromLinkedListNew(this.funcs).visitAll((it) -> LinkedListSequence.fromLinkedListNew(newState.funcs).addElement(it));
    LinkedListSequence.fromLinkedListNew(this.locals).visitAll((it) -> LinkedListSequence.fromLinkedListNew(newState.locals).addElement(it));

    return newState;
  }

  public void addFunc(SNode func) {
    LinkedListSequence.fromLinkedListNew(this.funcs).addElement(func);
  }

  public int funcIdx(SNode func) {
    return LinkedListSequence.fromLinkedListNew(this.funcs).indexOf(func);
  }

  public void addLocal(SNode local) {
    LinkedListSequence.fromLinkedListNew(this.locals).addElement(local);
  }

  public int localIdx(final SNode local) {
    SNode found = LinkedListSequence.fromLinkedListNew(this.locals).findFirst((l) -> LocalIndexed__BehaviorDescriptor.name_id7K_nJtkyL3W.invoke(l).equals(LocalIndexed__BehaviorDescriptor.name_id7K_nJtkyL3W.invoke(local)));
    return LinkedListSequence.fromLinkedListNew(this.locals).indexOf(found);
  }

}
