package CoryLang.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.style.AbstractStyleClass;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.editor.runtime.descriptor.EditorBuilderEnvironment;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.MPSColors;

public class CoryLangMain_StyleSheet {
  public static class identifierStyleClass extends AbstractStyleClass {
    public identifierStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public identifierStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.LIGHT_BLUE));
    }

  }
  public static class typeStyleClass extends AbstractStyleClass {
    public typeStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public typeStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.magenta));
    }

  }
  public static class exprnameStyleClass extends AbstractStyleClass {
    public exprnameStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public exprnameStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.red));
    }

  }
  public static class labelStyleClass extends AbstractStyleClass {
    public labelStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public labelStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.DARK_MAGENTA));
    }

  }
}
