package CoryLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ValueType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ValueType() {
    super(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL, "ValueType", "r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651121870156");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_i32_0 = new EnumerationDescriptor.MemberDescriptor("i32", "i32", 0x7c255ef74f4f054dL, "r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651121870157");
  private final EnumerationDescriptor.MemberDescriptor myMember_i64_0 = new EnumerationDescriptor.MemberDescriptor("i64", "i64", 0x7c255ef74f4f0580L, "r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651121870208");
  private final EnumerationDescriptor.MemberDescriptor myMember_f32_0 = new EnumerationDescriptor.MemberDescriptor("f32", "f32", 0x7c255ef74f4f058dL, "r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651121870221");
  private final EnumerationDescriptor.MemberDescriptor myMember_f64_0 = new EnumerationDescriptor.MemberDescriptor("f64", "f64", 0x7c255ef74f4f05a5L, "r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651121870245");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL, 0x7c255ef74f4f054dL, 0x7c255ef74f4f0580L, 0x7c255ef74f4f058dL, 0x7c255ef74f4f05a5L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_i32_0, myMember_i64_0, myMember_f32_0, myMember_f64_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "i32":
        return myMember_i32_0;
      case "i64":
        return myMember_i64_0;
      case "f32":
        return myMember_f32_0;
      case "f64":
        return myMember_f64_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
