package CoryLang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Const = 0;
  public static final int EmptyStatement = 1;
  public static final int Expression = 2;
  public static final int F32 = 3;
  public static final int F64 = 4;
  public static final int Function = 5;
  public static final int I32 = 6;
  public static final int I64 = 7;
  public static final int Module = 8;
  public static final int ModuleBodyElem = 9;
  public static final int Name = 10;
  public static final int ParamOrResult = 11;
  public static final int Statement = 12;
  public static final int Type = 13;
  public static final int Value = 14;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xbe6061dd252a45b8L, 0x9db81233f2660809L);
    builder.put(0x39e7fc40f9b5e373L, Const);
    builder.put(0x39e7fc40f9b5e404L, EmptyStatement);
    builder.put(0x39e7fc40f9b5e3e6L, Expression);
    builder.put(0x39e7fc40f9b5e36eL, F32);
    builder.put(0x39e7fc40f9b5e36fL, F64);
    builder.put(0x39e7fc40f9b5e368L, Function);
    builder.put(0x39e7fc40f9b5e36cL, I32);
    builder.put(0x39e7fc40f9b5e36dL, I64);
    builder.put(0x39e7fc40f9b5e367L, Module);
    builder.put(0x39e7fc40f9b65bcbL, ModuleBodyElem);
    builder.put(0x7c255ef74f4f0932L, Name);
    builder.put(0x7c255ef74f4f0792L, ParamOrResult);
    builder.put(0x39e7fc40f9b5e3e7L, Statement);
    builder.put(0x39e7fc40f9b5e370L, Type);
    builder.put(0x39e7fc40f9b5e369L, Value);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
