package CoryLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAnnotation = createDescriptorForAnnotation();
  /*package*/ final ConceptDescriptor myConceptConst = createDescriptorForConst();
  /*package*/ final ConceptDescriptor myConceptEmptyStatement = createDescriptorForEmptyStatement();
  /*package*/ final ConceptDescriptor myConceptExportAnnotation = createDescriptorForExportAnnotation();
  /*package*/ final ConceptDescriptor myConceptExpression = createDescriptorForExpression();
  /*package*/ final ConceptDescriptor myConceptF32 = createDescriptorForF32();
  /*package*/ final ConceptDescriptor myConceptF64 = createDescriptorForF64();
  /*package*/ final ConceptDescriptor myConceptFuncCall = createDescriptorForFuncCall();
  /*package*/ final ConceptDescriptor myConceptFunction = createDescriptorForFunction();
  /*package*/ final ConceptDescriptor myConceptI32 = createDescriptorForI32();
  /*package*/ final ConceptDescriptor myConceptI64 = createDescriptorForI64();
  /*package*/ final ConceptDescriptor myConceptImport = createDescriptorForImport();
  /*package*/ final ConceptDescriptor myConceptLabel = createDescriptorForLabel();
  /*package*/ final ConceptDescriptor myConceptModule = createDescriptorForModule();
  /*package*/ final ConceptDescriptor myConceptModuleBodyElem = createDescriptorForModuleBodyElem();
  /*package*/ final ConceptDescriptor myConceptName = createDescriptorForName();
  /*package*/ final ConceptDescriptor myConceptParamOrResult = createDescriptorForParamOrResult();
  /*package*/ final ConceptDescriptor myConceptStatement = createDescriptorForStatement();
  /*package*/ final ConceptDescriptor myConceptType = createDescriptorForType();
  /*package*/ final ConceptDescriptor myConceptValue = createDescriptorForValue();
  /*package*/ final EnumerationDescriptor myEnumerationValueType = new EnumerationDescriptor_ValueType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAnnotation, myConceptConst, myConceptEmptyStatement, myConceptExportAnnotation, myConceptExpression, myConceptF32, myConceptF64, myConceptFuncCall, myConceptFunction, myConceptI32, myConceptI64, myConceptImport, myConceptLabel, myConceptModule, myConceptModuleBodyElem, myConceptName, myConceptParamOrResult, myConceptStatement, myConceptType, myConceptValue);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Annotation:
        return myConceptAnnotation;
      case LanguageConceptSwitch.Const:
        return myConceptConst;
      case LanguageConceptSwitch.EmptyStatement:
        return myConceptEmptyStatement;
      case LanguageConceptSwitch.ExportAnnotation:
        return myConceptExportAnnotation;
      case LanguageConceptSwitch.Expression:
        return myConceptExpression;
      case LanguageConceptSwitch.F32:
        return myConceptF32;
      case LanguageConceptSwitch.F64:
        return myConceptF64;
      case LanguageConceptSwitch.FuncCall:
        return myConceptFuncCall;
      case LanguageConceptSwitch.Function:
        return myConceptFunction;
      case LanguageConceptSwitch.I32:
        return myConceptI32;
      case LanguageConceptSwitch.I64:
        return myConceptI64;
      case LanguageConceptSwitch.Import:
        return myConceptImport;
      case LanguageConceptSwitch.Label:
        return myConceptLabel;
      case LanguageConceptSwitch.Module:
        return myConceptModule;
      case LanguageConceptSwitch.ModuleBodyElem:
        return myConceptModuleBodyElem;
      case LanguageConceptSwitch.Name:
        return myConceptName;
      case LanguageConceptSwitch.ParamOrResult:
        return myConceptParamOrResult;
      case LanguageConceptSwitch.Statement:
        return myConceptStatement;
      case LanguageConceptSwitch.Type:
        return myConceptType;
      case LanguageConceptSwitch.Value:
        return myConceptValue;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationValueType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Annotation", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef7505d9992L);
    b.class_(false, true, false);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651139602834");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConst() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Const", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e373L);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Value
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e369L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607411");
    b.version(3);
    b.property("content", 0x39e7fc40f9b5e376L).type(PrimitiveTypeId.STRING).origin("4172580935779607414").done();
    b.property("valType", 0x7c255ef750435947L).type(MetaIdFactory.dataTypeId(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL)).origin("8945660651137882439").done();
    b.alias("const");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEmptyStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "EmptyStatement", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e404L);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Statement
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e3e7L);
    b.parent(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b65bcbL);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607556");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExportAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "ExportAnnotation", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef7505d9a8bL);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Annotation
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef7505d9992L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651139603083");
    b.version(3);
    b.alias("@export");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExpression() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Expression", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e3e6L);
    b.class_(false, true, false);
    // extends: CoryLang.structure.Statement
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e3e7L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607526");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForF32() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "F32", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e36eL);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Type
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e370L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607406");
    b.version(3);
    b.alias("f32");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForF64() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "F64", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e36fL);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Type
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e370L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607407");
    b.version(3);
    b.alias("f64");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFuncCall() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "FuncCall", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef750754c74L);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Expression
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e3e6L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651141155956");
    b.version(3);
    b.aggregate("name", 0x7c255ef750754d34L).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0932L).optional(false).ordered(true).multiple(false).origin("8945660651141156148").done();
    b.aggregate("params", 0x7c255ef750754d5fL).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e369L).optional(true).ordered(true).multiple(true).origin("8945660651141156191").done();
    b.alias("call");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Function", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e368L);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Expression
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e3e6L);
    b.parent(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b65bcbL);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607400");
    b.version(3);
    b.aggregate("name", 0x7c255ef74f4f0c5cL).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0932L).optional(false).ordered(true).multiple(false).origin("8945660651121871964").done();
    b.aggregate("annotations", 0x7c255ef7505e5e61L).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef7505d9992L).optional(true).ordered(true).multiple(true).origin("8945660651139653217").done();
    b.aggregate("params", 0x7c255ef74f4f0836L).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0792L).optional(true).ordered(true).multiple(true).origin("8945660651121870902").done();
    b.aggregate("results", 0x7c255ef74f4f0875L).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0792L).optional(true).ordered(true).multiple(true).origin("8945660651121870965").done();
    b.aggregate("body", 0x39e7fc40f9b5ff91L).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e3e7L).optional(true).ordered(true).multiple(true).origin("4172580935779614609").done();
    b.alias("func");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForI32() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "I32", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e36cL);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Type
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e370L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607404");
    b.version(3);
    b.alias("i32");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForI64() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "I64", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e36dL);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Type
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e370L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607405");
    b.version(3);
    b.alias("i64");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForImport() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Import", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef750704824L);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Expression
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e3e6L);
    b.parent(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b65bcbL);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651140827172");
    b.version(3);
    b.property("module_name", 0x7c255ef750704e14L).type(PrimitiveTypeId.STRING).origin("8945660651140828692").done();
    b.property("func_name", 0x7c255ef750704e3eL).type(PrimitiveTypeId.STRING).origin("8945660651140828734").done();
    b.aggregate("name", 0x7c255ef750704da8L).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0932L).optional(false).ordered(true).multiple(false).origin("8945660651140828584").done();
    b.aggregate("params", 0x7c255ef750704960L).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0792L).optional(true).ordered(true).multiple(true).origin("8945660651140827488").done();
    b.aggregate("results", 0x7c255ef7507049b9L).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0792L).optional(true).ordered(true).multiple(true).origin("8945660651140827577").done();
    b.alias("import");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLabel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Label", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef750768d1aL);
    b.class_(false, false, false);
    // extends: CoryLang.structure.Value
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e369L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651141238042");
    b.version(3);
    b.aggregate("name", 0x7c255ef750768d4dL).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0932L).optional(false).ordered(true).multiple(false).origin("8945660651141238093").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Module", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e367L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607399");
    b.version(3);
    b.aggregate("statements", 0x39e7fc40f9b5e3eaL).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b65bcbL).optional(true).ordered(true).multiple(true).origin("4172580935779607530").done();
    b.alias("module");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModuleBodyElem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "ModuleBodyElem", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b65bcbL);
    b.interface_();
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779638219");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForName() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Name", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0932L);
    b.class_(false, false, false);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651121871154");
    b.version(3);
    b.property("value", 0x7c255ef74f4f096fL).type(PrimitiveTypeId.STRING).origin("8945660651121871215").done();
    b.alias("name");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParamOrResult() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "ParamOrResult", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0792L);
    b.class_(false, false, false);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/8945660651121870738");
    b.version(3);
    b.property("type", 0x7c255ef74f4f0801L).type(MetaIdFactory.dataTypeId(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL)).origin("8945660651121870849").done();
    b.aggregate("label", 0x7c255ef74f4f09a5L).target(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef750768d1aL).optional(false).ordered(true).multiple(false).origin("8945660651121871269").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Statement", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e3e7L);
    b.class_(false, false, false);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607527");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Type", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e370L);
    b.class_(false, true, false);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607408");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CoryLang", "Value", 0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e369L);
    b.class_(false, true, false);
    // extends: CoryLang.structure.Expression
    b.super_(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e3e6L);
    b.origin("r:49f73168-bdae-44eb-95b8-66b51141f222(CoryLang.structure)/4172580935779607401");
    b.version(3);
    b.property("type", 0x7c255ef74f4f05e7L).type(MetaIdFactory.dataTypeId(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL)).origin("8945660651121870311").done();
    return b.create();
  }
}
