package CoryLang.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public class typeof_LabelReference_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_LabelReference_InferenceRule() {
  }
  public void applyRule(final SNode labelReference, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    SNode labelParam = SNodeOperations.getNodeAncestor(SLinkOperations.getTarget(labelReference, LINKS.label$KC5l), CONCEPTS.ParamOrResult$F$, false, false);

    if ((labelParam != null) && SPropertyOperations.getEnum(labelParam, PROPS.type$RW2q) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL, "CoryLang.structure.ValueType"), 0x7c255ef74f4f054dL, "i32")) {
      {
        SNode _nodeToCheck_1029348928467 = labelReference;
        EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:9ddd07c5-2599-42c8-a119-ecda288c2c8e(CoryLang.typesystem)", "8945660651240240612", 0, null);
        typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:9ddd07c5-2599-42c8-a119-ecda288c2c8e(CoryLang.typesystem)", "8945660651240240105", true), (SNode) SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e36cL, "CoryLang.structure.I32")), _info_12389875345);
      }
    } else if ((labelParam != null) && SPropertyOperations.getEnum(labelParam, PROPS.type$RW2q) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL, "CoryLang.structure.ValueType"), 0x7c255ef74f4f0580L, "i64")) {
      {
        SNode _nodeToCheck_1029348928467 = labelReference;
        EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:9ddd07c5-2599-42c8-a119-ecda288c2c8e(CoryLang.typesystem)", "8945660651240257720", 0, null);
        typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:9ddd07c5-2599-42c8-a119-ecda288c2c8e(CoryLang.typesystem)", "8945660651240257726", true), (SNode) SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e36dL, "CoryLang.structure.I64")), _info_12389875345);
      }
    } else if ((labelParam != null) && SPropertyOperations.getEnum(labelParam, PROPS.type$RW2q) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL, "CoryLang.structure.ValueType"), 0x7c255ef74f4f058dL, "f32")) {
      {
        SNode _nodeToCheck_1029348928467 = labelReference;
        EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:9ddd07c5-2599-42c8-a119-ecda288c2c8e(CoryLang.typesystem)", "8945660651240257863", 0, null);
        typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:9ddd07c5-2599-42c8-a119-ecda288c2c8e(CoryLang.typesystem)", "8945660651240257869", true), (SNode) SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e36eL, "CoryLang.structure.F32")), _info_12389875345);
      }
    } else if ((labelParam != null) && SPropertyOperations.getEnum(labelParam, PROPS.type$RW2q) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f054cL, "CoryLang.structure.ValueType"), 0x7c255ef74f4f05a5L, "f64")) {
      {
        SNode _nodeToCheck_1029348928467 = labelReference;
        EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:9ddd07c5-2599-42c8-a119-ecda288c2c8e(CoryLang.typesystem)", "8945660651240258309", 0, null);
        typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:9ddd07c5-2599-42c8-a119-ecda288c2c8e(CoryLang.typesystem)", "8945660651240258315", true), (SNode) SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x39e7fc40f9b5e36fL, "CoryLang.structure.F64")), _info_12389875345);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.LabelReference$Zd;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink label$KC5l = MetaAdapterFactory.getReferenceLink(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef754f7e6a4L, 0x7c255ef754f7e6edL, "label");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ParamOrResult$F$ = MetaAdapterFactory.getConcept(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0792L, "CoryLang.structure.ParamOrResult");
    /*package*/ static final SConcept LabelReference$Zd = MetaAdapterFactory.getConcept(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef754f7e6a4L, "CoryLang.structure.LabelReference");
  }

  private static final class PROPS {
    /*package*/ static final SProperty type$RW2q = MetaAdapterFactory.getProperty(0xbe6061dd252a45b8L, 0x9db81233f2660809L, 0x7c255ef74f4f0792L, 0x7c255ef74f4f0801L, "type");
  }
}
